export const offlineSeed = {
  childProfiles: [
    {
      id: "seed_child_grade7",
      parent_email: "offline@zamaai.local",
      child_name: "Offline Learner",
      grade: "Grade 7",
      is_active: true,
      created_date: "2026-01-01T00:00:00.000Z",
    },
  ],
  subjects: [
    {
      id: "seed_subject_maths_g7",
      name: "Mathematics",
      grade: "Grade 7",
      icon: "➗",
      color: "violet",
      description: "Numbers, shapes, measurements, and problem solving.",
      is_active: true,
    },
    {
      id: "seed_subject_english_g7",
      name: "English",
      grade: "Grade 7",
      icon: "📘",
      color: "blue",
      description: "Reading, grammar, vocabulary, and writing skills.",
      is_active: true,
    },
    {
      id: "seed_subject_science_g7",
      name: "Science",
      grade: "Grade 7",
      icon: "🔬",
      color: "emerald",
      description: "Living things, matter, energy, and the environment.",
      is_active: true,
    },
    {
      id: "seed_subject_social_g7",
      name: "Social Studies",
      grade: "Grade 7",
      icon: "Map",
      color: "amber",
      description: "Zimbabwe, maps, history, communities, and citizenship.",
      is_active: true,
    },
  ],
  topics: [
    {
      id: "seed_topic_fractions",
      subject_id: "seed_subject_maths_g7",
      name: "Fractions",
      order: 1,
      learning_objectives: "Compare fractions and solve simple sharing problems.",
      description: "Learn how fractions show parts of a whole.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_area",
      subject_id: "seed_subject_maths_g7",
      name: "Area and Perimeter",
      order: 2,
      learning_objectives: "Find distance around a shape and space inside it.",
      description: "Use rectangles and real-life measurements.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_decimals",
      subject_id: "seed_subject_maths_g7",
      name: "Decimals and Money",
      order: 3,
      learning_objectives: "Read decimals and solve simple money problems.",
      description: "Use cents, dollars, and place value.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_percentages",
      subject_id: "seed_subject_maths_g7",
      name: "Percentages",
      order: 4,
      learning_objectives: "Find simple percentages of quantities.",
      description: "Practise discounts, scores, and shares out of 100.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_comprehension",
      subject_id: "seed_subject_english_g7",
      name: "Reading Comprehension",
      order: 1,
      learning_objectives: "Read a short passage and answer questions from it.",
      description: "Practise finding facts and meaning in a passage.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_parts_of_speech",
      subject_id: "seed_subject_english_g7",
      name: "Parts of Speech",
      order: 2,
      learning_objectives: "Identify nouns, verbs, adjectives, and adverbs.",
      description: "Build stronger sentences by naming word jobs.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_composition",
      subject_id: "seed_subject_english_g7",
      name: "Composition Writing",
      order: 3,
      learning_objectives: "Plan and write a clear short composition.",
      description: "Use beginning, middle, ending, and descriptive details.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_plants",
      subject_id: "seed_subject_science_g7",
      name: "Plant Growth",
      order: 1,
      learning_objectives: "Identify what plants need to grow well.",
      description: "Explore water, sunlight, air, soil, and healthy plants.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_human_body",
      subject_id: "seed_subject_science_g7",
      name: "Human Body Systems",
      order: 2,
      learning_objectives: "Describe basic body systems and their functions.",
      description: "Learn about breathing, digestion, blood, and healthy habits.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_water_cycle",
      subject_id: "seed_subject_science_g7",
      name: "Water Cycle",
      order: 3,
      learning_objectives: "Explain how water moves through nature.",
      description: "Study evaporation, condensation, rain, and collection.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_maps",
      subject_id: "seed_subject_social_g7",
      name: "Maps and Directions",
      order: 1,
      learning_objectives: "Use symbols, scale, compass points, and simple maps.",
      description: "Read maps for school, town, district, and country.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_zimbabwe_history",
      subject_id: "seed_subject_social_g7",
      name: "Zimbabwe History",
      order: 2,
      learning_objectives: "Identify important places and events in Zimbabwe history.",
      description: "Learn about Great Zimbabwe, independence, and national heritage.",
      is_free: true,
      is_active: true,
    },
  ],
  notes: [
    {
      id: "seed_note_fractions",
      topic_id: "seed_topic_fractions",
      subject_id: "seed_subject_maths_g7",
      overview: "A fraction shows part of a whole. If a sadza pot is shared into 4 equal parts, one part is 1/4.",
      key_definitions: "- Whole: the complete thing.\n- Equal parts: parts with the same size.\n- Fraction: one or more equal parts of a whole.",
      key_concepts: "To compare fractions, first check if the bottom numbers are the same. If they are the same, the bigger top number is the bigger fraction.",
      concept_examples: [
        {
          concept: "Sharing equally",
          examples: [
            { difficulty: "Easy", problem: "Tariro eats 1/4 of a mango. What fraction is eaten?", solution: "Step 1: The mango has 4 equal parts. Step 2: Tariro eats 1 part. Answer = 1/4." },
            { difficulty: "Standard", problem: "A cake is cut into 8 equal pieces. Tendai eats 3 pieces. What fraction is eaten?", solution: "Step 1: There are 8 pieces. Step 2: Tendai eats 3 pieces. Answer = 3/8." },
            { difficulty: "Hard", problem: "A farmer shares 12 oranges equally among 4 children. What fraction of all oranges does one child get?", solution: "Step 1: One child gets 3 oranges. Step 2: 3 out of 12 is 3/12. Step 3: 3/12 is the same as 1/4. Answer = 1/4." }
          ]
        }
      ],
      zimbabwe_examples: "Fractions are used when sharing sadza, cutting fruit, measuring mealie meal, or splitting bus fare.",
      important_facts: "- Fractions must have equal parts.\n- The top number counts selected parts.\n- The bottom number counts all equal parts.\n- Bigger bottom numbers can mean smaller pieces.",
      common_mistakes: "Do not compare only the bottom number. 1/2 is bigger than 1/4 because half is larger than a quarter.",
      summary: "- A fraction is part of a whole.\n- Parts must be equal.\n- 1/2 means one of two equal parts.\n- 3/4 means three of four equal parts.\n- Draw pictures when unsure.",
      exam_tips: "Draw the whole first. Split it into equal parts. Shade the parts asked for. Check your answer.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_area",
      topic_id: "seed_topic_area",
      subject_id: "seed_subject_maths_g7",
      overview: "Perimeter is the distance around a shape. Area is the space inside a shape.",
      key_definitions: "- Perimeter: distance around a shape.\n- Area: space inside a shape.\n- Length: the longer side of a rectangle.\n- Width: the shorter side of a rectangle.\n- Square unit: the unit used for area.",
      key_concepts: "To find perimeter, add all sides. To find the area of a rectangle, multiply length by width. Always write the correct unit.",
      concept_examples: [
        {
          concept: "Rectangles",
          examples: [
            { difficulty: "Easy", problem: "A garden is 5 m long and 3 m wide. What is its area?", solution: "Step 1: Area = length x width. Step 2: 5 x 3 = 15. Answer = 15 square metres." },
            { difficulty: "Standard", problem: "A classroom is 8 m long and 4 m wide. What is its perimeter?", solution: "Step 1: Perimeter = 8 + 4 + 8 + 4. Step 2: Add the sides. Step 3: Total = 24. Answer = 24 m." },
            { difficulty: "Advanced", problem: "A chicken run is 6 m by 5 m. How much wire is needed around it?", solution: "Step 1: Wire goes around the outside. Step 2: Perimeter = 6 + 5 + 6 + 5. Step 3: Total = 22. Answer = 22 m of wire." }
          ]
        }
      ],
      zimbabwe_examples: "Area and perimeter are useful when fencing a garden, tiling a room, or measuring a school field.",
      important_facts: "- Perimeter is around.\n- Area is inside.\n- Rectangle area = length x width.\n- Perimeter uses units like m, area uses square units.",
      common_mistakes: "Do not mix area and perimeter. Area is not found by adding all sides.",
      summary: "- Perimeter means around.\n- Area means inside.\n- Add sides for perimeter.\n- Multiply length by width for rectangle area.\n- Use the correct units.",
      exam_tips: "Underline whether the question asks for area or perimeter before calculating.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_comprehension",
      topic_id: "seed_topic_comprehension",
      subject_id: "seed_subject_english_g7",
      overview: "Comprehension means understanding what you read. Read slowly and look for answers in the passage.",
      key_definitions: "- Passage: the text you read.\n- Main idea: what the passage is mostly about.\n- Detail: a small fact from the passage.",
      key_concepts: "Read the question first. Then scan the passage for key words. Use evidence from the passage.",
      concept_examples: [
        {
          concept: "Finding evidence",
          examples: [
            { difficulty: "Easy", problem: "A passage says Nyasha watered maize every morning. Who watered maize?", solution: "Step 1: Find the word watered. Step 2: Read the sentence. Answer = Nyasha." },
            { difficulty: "Standard", problem: "A story says rain clouds gathered, then pupils ran home. Why did they run?", solution: "Step 1: Look before the action. Step 2: Rain clouds gathered. Answer = They thought it would rain." },
            { difficulty: "Hard", problem: "A character shares food with a friend. What does this show?", solution: "Step 1: Notice the action. Step 2: Sharing helps someone. Step 3: This shows kindness. Answer = The character is kind." }
          ]
        }
      ],
      zimbabwe_examples: "You can read stories about school, markets, farms, buses, and family life in Zimbabwe.",
      important_facts: "- Read twice.\n- Underline key words.\n- Use the passage.\n- Do not guess before reading.",
      common_mistakes: "Do not answer from your own ideas only. The answer must match the passage.",
      summary: "- Read the question.\n- Find key words.\n- Read nearby sentences.\n- Choose the best answer.\n- Check again.",
      exam_tips: "If stuck, skip and come back. Answers often appear near the same words used in the question.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_plants",
      topic_id: "seed_topic_plants",
      subject_id: "seed_subject_science_g7",
      overview: "Plants are living things. They need water, sunlight, air, and good soil to grow well.",
      key_definitions: "- Roots: the part that takes in water from the soil.\n- Stem: the part that holds the plant upright.\n- Leaves: the parts that help the plant make food.\n- Germination: when a seed starts to grow.\n- Seedling: a young plant.",
      key_concepts: "A plant starts as a seed. With water and warmth, the seed opens and grows roots and a shoot. The leaves use sunlight, air, and water to help the plant make food.",
      concept_examples: [
        {
          concept: "What plants need",
          examples: [
            { difficulty: "Easy", problem: "Tariro puts one bean seed in dry soil and one in moist soil. Which seed is more likely to grow?", solution: "Step 1: A seed needs water to start growing. Step 2: Moist soil has water. Answer = The seed in moist soil is more likely to grow." },
            { difficulty: "Standard", problem: "A maize plant has water but is kept in a dark room. Why will it grow poorly?", solution: "Step 1: Green plants need sunlight. Step 2: Sunlight helps leaves make food. Step 3: A dark room has little sunlight. Answer = It will not make enough food." },
            { difficulty: "Advanced", problem: "A school garden has two tomato plants. Plant A gets water and sunlight. Plant B gets water only. Which plant will be healthier after two weeks?", solution: "Step 1: Both plants get water. Step 2: Only Plant A gets sunlight. Step 3: Sunlight helps plants make food. Answer = Plant A will be healthier." }
          ]
        }
      ],
      zimbabwe_examples: "Farmers in Zimbabwe plant maize when there is enough rain. Vegetable gardens need watering in dry months. Pupils can grow beans in cups to observe roots and shoots.",
      important_facts: "- Plants need water, sunlight, air, and soil.\n- Roots take in water.\n- Leaves help the plant make food.\n- Healthy plants grow better in good conditions.",
      common_mistakes: "Do not think water alone is enough. A plant also needs sunlight and air. Do not pull seedlings from the soil when observing them.",
      summary: "- A seed can grow into a plant.\n- Water helps seeds start growing.\n- Roots take in water.\n- Leaves help make food.\n- Sunlight helps plants grow strong.",
      exam_tips: "Name the plant part asked for. Use words like roots, stem, leaves, water, sunlight, and air. Read diagrams carefully.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_decimals",
      topic_id: "seed_topic_decimals",
      subject_id: "seed_subject_maths_g7",
      overview: "Decimals show parts of a whole using a point. Money uses decimals when cents are written after dollars.",
      key_definitions: "- Decimal point: the dot that separates whole numbers and parts.\n- Tenths: one whole split into 10 equal parts.\n- Hundredths: one whole split into 100 equal parts.\n- Place value: the value of a digit because of its position.",
      key_concepts: "Read the whole number first, then read the decimal part. In money, 3.50 means 3 dollars and 50 cents. Line up decimal points when adding money.",
      concept_examples: [
        {
          concept: "Adding money",
          examples: [
            { difficulty: "Easy", problem: "A pen costs $0.50 and a ruler costs $0.30. What is the total cost?", solution: "Step 1: Add cents. Step 2: 50 cents + 30 cents = 80 cents. Answer = $0.80." },
            { difficulty: "Standard", problem: "Bus fare is $1.25 and a snack is $0.75. How much is spent?", solution: "Step 1: Line up decimal points. Step 2: 1.25 + 0.75 = 2.00. Answer = $2.00." },
            { difficulty: "Advanced", problem: "Tendai has $5.00. He buys mealie meal for $2.40 and tomatoes for $1.35. How much remains?", solution: "Step 1: Add costs. Step 2: 2.40 + 1.35 = 3.75. Step 3: 5.00 - 3.75 = 1.25. Answer = $1.25." }
          ]
        }
      ],
      zimbabwe_examples: "Decimals are useful when shopping at a tuckshop, paying bus fare, or measuring lengths in metres.",
      important_facts: "- Keep decimal points in a straight column.\n- Two decimal places are often used for money.\n- 0.5 is the same as 0.50.\n- Check if your answer is reasonable.",
      common_mistakes: "Do not ignore zeroes in money. $2.05 is not the same as $2.50.",
      summary: "- Decimals show parts of a whole.\n- Money often uses two decimal places.\n- Line up decimal points.\n- Add or subtract carefully.\n- Estimate to check your answer.",
      exam_tips: "Write money with two digits after the decimal point. Show working for addition and subtraction.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_percentages",
      topic_id: "seed_topic_percentages",
      subject_id: "seed_subject_maths_g7",
      overview: "A percentage means out of 100. It helps compare marks, discounts, and parts of a group.",
      key_definitions: "- Percent: out of 100.\n- Discount: money taken off a price.\n- Total: the whole amount.\n- Score: marks gained in a test.",
      key_concepts: "To find 10 percent, divide by 10. To find 50 percent, divide by 2. To find 25 percent, divide by 4.",
      concept_examples: [
        {
          concept: "Finding simple percentages",
          examples: [
            { difficulty: "Easy", problem: "What is 50 percent of 20 mangoes?", solution: "Step 1: 50 percent means half. Step 2: Half of 20 is 10. Answer = 10 mangoes." },
            { difficulty: "Standard", problem: "A book costs $10. It has a 10 percent discount. How much is taken off?", solution: "Step 1: 10 percent means divide by 10. Step 2: 10 / 10 = 1. Answer = $1 discount." },
            { difficulty: "Advanced", problem: "A pupil scores 18 out of 20. What percentage is this?", solution: "Step 1: Make the score out of 100. Step 2: 20 x 5 = 100. Step 3: 18 x 5 = 90. Answer = 90 percent." }
          ]
        }
      ],
      zimbabwe_examples: "Percentages are used in school marks, shop discounts, battery charge, and rainfall reports.",
      important_facts: "- Percent means out of 100.\n- 50 percent is half.\n- 25 percent is a quarter.\n- 10 percent is one tenth.",
      common_mistakes: "Do not add a percent sign to every answer. Use it only when the answer is a percentage.",
      summary: "- Percent means out of 100.\n- Divide by 2 for 50 percent.\n- Divide by 4 for 25 percent.\n- Divide by 10 for 10 percent.\n- Always read the question carefully.",
      exam_tips: "Look for easy percentages first. Convert marks to out of 100 when needed.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_parts_of_speech",
      topic_id: "seed_topic_parts_of_speech",
      subject_id: "seed_subject_english_g7",
      overview: "Words have different jobs in a sentence. Parts of speech help you understand and write better sentences.",
      key_definitions: "- Noun: a name of a person, place, animal, or thing.\n- Verb: an action word.\n- Adjective: a word that describes a noun.\n- Adverb: a word that describes a verb.",
      key_concepts: "Find the action first. Then find who or what does it. Add describing words to make the sentence clearer.",
      concept_examples: [
        {
          concept: "Word jobs",
          examples: [
            { difficulty: "Easy", problem: "In 'Rudo runs', which word is the verb?", solution: "Step 1: Look for the action. Step 2: Runs is the action. Answer = runs." },
            { difficulty: "Standard", problem: "In 'The tall boy carried maize', which word is the adjective?", solution: "Step 1: Find the noun boy. Step 2: Tall describes boy. Answer = tall." },
            { difficulty: "Advanced", problem: "In 'Nyasha quickly swept the classroom', name the adverb.", solution: "Step 1: Find the verb swept. Step 2: Quickly tells how she swept. Answer = quickly." }
          ]
        }
      ],
      zimbabwe_examples: "You can describe a busy market, a dusty road, a fast bus, or a helpful teacher.",
      important_facts: "- A noun names something.\n- A verb shows action.\n- An adjective describes a noun.\n- An adverb often tells how an action happens.",
      common_mistakes: "Do not call every describing word an adjective. If it describes an action, it may be an adverb.",
      summary: "- Words have jobs.\n- Nouns name things.\n- Verbs show actions.\n- Adjectives describe nouns.\n- Adverbs describe verbs.",
      exam_tips: "Underline the word first. Ask what job it does in the sentence.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_composition",
      topic_id: "seed_topic_composition",
      subject_id: "seed_subject_english_g7",
      overview: "A composition is a short piece of writing. Good writing has a clear beginning, middle, and ending.",
      key_definitions: "- Plan: short notes before writing.\n- Paragraph: a group of sentences about one idea.\n- Setting: where and when the story happens.\n- Characters: people or animals in a story.",
      key_concepts: "Plan before writing. Start by introducing the topic or story. Use the middle for details, then end clearly.",
      concept_examples: [
        {
          concept: "Planning a composition",
          examples: [
            { difficulty: "Easy", problem: "Write a plan for 'A day at the market'. What can the first paragraph say?", solution: "Step 1: Name the place. Step 2: Say who went there. Answer = I went to the market with my aunt." },
            { difficulty: "Standard", problem: "What details can you add about Mbare market?", solution: "Step 1: Think of sounds. Step 2: Think of people and goods. Step 3: Describe colours and movement. Answer = Add sights, sounds, and actions." },
            { difficulty: "Advanced", problem: "How can you end a story about helping a lost child?", solution: "Step 1: Solve the problem. Step 2: Show how people feel. Step 3: Add a final lesson. Answer = End with the child safe and everyone relieved." }
          ]
        }
      ],
      zimbabwe_examples: "Composition topics may include school events, markets, farms, buses, family visits, or rainy days.",
      important_facts: "- Plan before writing.\n- Use paragraphs.\n- Stay on the topic.\n- Check spelling and punctuation.",
      common_mistakes: "Do not start writing without a plan. Do not mix many unrelated ideas in one paragraph.",
      summary: "- A composition needs a plan.\n- Use a beginning, middle, and ending.\n- Add clear details.\n- Use paragraphs.\n- Read your work again.",
      exam_tips: "Spend a few minutes planning. Leave time to check grammar, spelling, and punctuation.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_human_body",
      topic_id: "seed_topic_human_body",
      subject_id: "seed_subject_science_g7",
      overview: "The human body has systems that work together. Each system has a special job that helps us stay alive and healthy.",
      key_definitions: "- Organ: a body part with a special job.\n- Digestion: breaking food into useful parts.\n- Breathing: taking air in and out.\n- Circulation: movement of blood around the body.",
      key_concepts: "The lungs help us breathe. The stomach helps digest food. The heart pumps blood around the body.",
      concept_examples: [
        {
          concept: "Body systems",
          examples: [
            { difficulty: "Easy", problem: "Which organ helps us breathe?", solution: "Step 1: Breathing uses air. Step 2: The lungs take in air. Answer = lungs." },
            { difficulty: "Standard", problem: "Why do pupils need food before sport?", solution: "Step 1: Food gives energy. Step 2: Sport needs energy. Answer = Food helps the body work during sport." },
            { difficulty: "Advanced", problem: "Why does the heart beat faster after running?", solution: "Step 1: Running makes muscles work harder. Step 2: Muscles need more oxygen. Step 3: Blood carries oxygen. Answer = The heart pumps faster to move more blood." }
          ]
        }
      ],
      zimbabwe_examples: "Healthy habits include drinking clean water, eating sadza with vegetables, washing hands, and exercising at school.",
      important_facts: "- Lungs help with breathing.\n- The heart pumps blood.\n- The stomach helps digest food.\n- Exercise and clean habits keep the body healthy.",
      common_mistakes: "Do not confuse the heart and lungs. The heart pumps blood. The lungs help with breathing.",
      summary: "- Body systems work together.\n- Lungs help us breathe.\n- The heart pumps blood.\n- Food gives energy.\n- Healthy habits protect the body.",
      exam_tips: "Use the correct organ name. Link each organ to its job.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_water_cycle",
      topic_id: "seed_topic_water_cycle",
      subject_id: "seed_subject_science_g7",
      overview: "The water cycle is how water moves around Earth. Heat from the sun helps water change and move.",
      key_definitions: "- Evaporation: liquid water changes into water vapour.\n- Condensation: water vapour cools and forms clouds.\n- Precipitation: water falls as rain, hail, or snow.\n- Collection: water gathers in rivers, dams, and lakes.",
      key_concepts: "The sun heats water in rivers and dams. Water vapour rises and cools into clouds. Clouds become heavy and rain falls.",
      concept_examples: [
        {
          concept: "Water movement",
          examples: [
            { difficulty: "Easy", problem: "What causes water in a puddle to dry after sunshine?", solution: "Step 1: The sun heats the water. Step 2: Water changes into vapour. Answer = evaporation." },
            { difficulty: "Standard", problem: "Clouds form over a mountain. Which process is happening?", solution: "Step 1: Water vapour cools. Step 2: Tiny drops form clouds. Answer = condensation." },
            { difficulty: "Advanced", problem: "Rain falls into a river that flows to a dam. Which stage is this?", solution: "Step 1: Rain has already fallen. Step 2: Water gathers in rivers and dams. Answer = collection." }
          ]
        }
      ],
      zimbabwe_examples: "Rain fills rivers, dams, and boreholes. Farmers depend on seasonal rainfall for crops like maize.",
      important_facts: "- The sun drives the water cycle.\n- Evaporation makes water vapour.\n- Condensation forms clouds.\n- Precipitation brings water back to the ground.",
      common_mistakes: "Do not say clouds are smoke. Clouds are made of tiny water drops or ice crystals.",
      summary: "- Water moves in a cycle.\n- The sun heats water.\n- Vapour forms clouds.\n- Rain falls from clouds.\n- Water collects in rivers and dams.",
      exam_tips: "Learn the order: evaporation, condensation, precipitation, collection.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_maps",
      topic_id: "seed_topic_maps",
      subject_id: "seed_subject_social_g7",
      overview: "A map is a drawing that shows places from above. Maps help people find directions and understand locations.",
      key_definitions: "- Compass: a tool or symbol that shows direction.\n- North: one main compass direction.\n- Symbol: a small picture that stands for something.\n- Scale: shows how map distance compares to real distance.\n- Key: explains map symbols.",
      key_concepts: "Start by finding the map title. Look at the key to understand symbols. Use compass points to describe direction.",
      concept_examples: [
        {
          concept: "Reading maps",
          examples: [
            { difficulty: "Easy", problem: "On a school map, a book symbol means library. What does the symbol show?", solution: "Step 1: Look at the key. Step 2: The key says book means library. Answer = library." },
            { difficulty: "Standard", problem: "The clinic is north of the school. Which direction do you walk from school?", solution: "Step 1: Find north on the compass. Step 2: Move from school towards north. Answer = north." },
            { difficulty: "Advanced", problem: "A map scale says 1 cm means 2 km. The road is 3 cm on the map. How long is the road?", solution: "Step 1: 1 cm means 2 km. Step 2: 3 cm means 3 x 2 km. Step 3: 3 x 2 = 6. Answer = 6 km." }
          ]
        }
      ],
      zimbabwe_examples: "Maps can show Harare, Bulawayo, rivers, roads, schools, clinics, districts, and provinces.",
      important_facts: "- A title tells what the map shows.\n- A key explains symbols.\n- A compass shows direction.\n- A scale helps estimate real distance.",
      common_mistakes: "Do not guess symbols. Always check the map key first.",
      summary: "- Maps show places from above.\n- Use the title first.\n- Use the key for symbols.\n- Use compass points for direction.\n- Use scale for distance.",
      exam_tips: "Check title, key, compass, and scale before answering map questions.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_zimbabwe_history",
      topic_id: "seed_topic_zimbabwe_history",
      subject_id: "seed_subject_social_g7",
      overview: "Zimbabwe has important historical places and events. Learning history helps us understand our country and heritage.",
      key_definitions: "- Heritage: important things passed from the past.\n- Monument: a place or building kept because it is important.\n- Independence: when a country governs itself.\n- Culture: the way people live, speak, dress, and celebrate.",
      key_concepts: "Great Zimbabwe is an important historical site. Independence Day is remembered on 18 April. National symbols remind citizens about unity and identity.",
      concept_examples: [
        {
          concept: "National heritage",
          examples: [
            { difficulty: "Easy", problem: "Which country is named after Great Zimbabwe?", solution: "Step 1: Great Zimbabwe is a historical site. Step 2: The country name is Zimbabwe. Answer = Zimbabwe." },
            { difficulty: "Standard", problem: "Why should people protect historical places?", solution: "Step 1: Historical places teach us about the past. Step 2: Future generations need to learn too. Answer = To preserve heritage." },
            { difficulty: "Advanced", problem: "How can schools help pupils respect national heritage?", solution: "Step 1: Teach history. Step 2: Visit monuments. Step 3: Discuss national symbols. Answer = Schools can teach, visit, and practise respect." }
          ]
        }
      ],
      zimbabwe_examples: "Examples include Great Zimbabwe, the national flag, Independence Day, heroes, traditional music, and local languages.",
      important_facts: "- Great Zimbabwe is a major heritage site.\n- Independence Day is 18 April.\n- Heritage should be protected.\n- National symbols show identity.",
      common_mistakes: "Do not confuse a monument with any ordinary building. A monument has special historical importance.",
      summary: "- History teaches about the past.\n- Heritage should be protected.\n- Great Zimbabwe is important.\n- Independence is remembered each year.\n- National symbols build unity.",
      exam_tips: "Use correct dates and names. Explain why heritage places are important.",
      is_ai_generated: false,
      is_active: true,
    },
  ],
  questions: [
    {
      id: "seed_q_fraction_1",
      topic_id: "seed_topic_fractions",
      subject_id: "seed_subject_maths_g7",
      question_text: "A mango is cut into 4 equal pieces. Rudo eats 1 piece. What fraction did she eat?",
      question_type: "mcq",
      options: [{ label: "A", text: "1/2" }, { label: "B", text: "1/4" }, { label: "C", text: "3/4" }, { label: "D", text: "4/1" }],
      correct_answer: "B",
      explanation: "She ate 1 out of 4 equal pieces, so the fraction is 1/4.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_fraction_2",
      topic_id: "seed_topic_fractions",
      subject_id: "seed_subject_maths_g7",
      question_text: "Which fraction is larger?",
      question_type: "mcq",
      options: [{ label: "A", text: "1/2" }, { label: "B", text: "1/4" }, { label: "C", text: "1/8" }, { label: "D", text: "1/10" }],
      correct_answer: "A",
      explanation: "One half is bigger than one quarter, one eighth, and one tenth.",
      difficulty: "Standard",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_area_1",
      topic_id: "seed_topic_area",
      subject_id: "seed_subject_maths_g7",
      question_text: "A rectangular garden is 6 m long and 4 m wide. What is its area?",
      question_type: "mcq",
      options: [{ label: "A", text: "10 m²" }, { label: "B", text: "20 m²" }, { label: "C", text: "24 m²" }, { label: "D", text: "26 m²" }],
      correct_answer: "C",
      explanation: "Area of a rectangle = length × width. 6 × 4 = 24 m².",
      difficulty: "Standard",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_comprehension_1",
      topic_id: "seed_topic_comprehension",
      subject_id: "seed_subject_english_g7",
      comprehension_passage: "Nyasha woke up early in Mutare. She helped her grandmother water the vegetable garden before school. The tomatoes were growing well because they had enough water and sunlight.",
      question_text: "Why were the tomatoes growing well?",
      question_type: "comprehension",
      options: [{ label: "A", text: "They had enough water and sunlight" }, { label: "B", text: "Nyasha slept late" }, { label: "C", text: "It was raining all day" }, { label: "D", text: "They were at school" }],
      correct_answer: "A",
      explanation: "The passage says the tomatoes had enough water and sunlight.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_plants_1",
      topic_id: "seed_topic_plants",
      subject_id: "seed_subject_science_g7",
      question_text: "Which of these do green plants need to make food?",
      question_type: "mcq",
      options: [{ label: "A", text: "Sunlight" }, { label: "B", text: "Plastic" }, { label: "C", text: "Smoke" }, { label: "D", text: "Salt only" }],
      correct_answer: "A",
      explanation: "Green plants need sunlight, air, and water to make food.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_decimal_1",
      topic_id: "seed_topic_decimals",
      subject_id: "seed_subject_maths_g7",
      question_text: "A pencil costs $0.40 and an exercise book costs $1.20. What is the total cost?",
      question_type: "mcq",
      options: [{ label: "A", text: "$1.40" }, { label: "B", text: "$1.60" }, { label: "C", text: "$2.40" }, { label: "D", text: "$0.80" }],
      correct_answer: "B",
      explanation: "$0.40 + $1.20 = $1.60.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_decimal_2",
      topic_id: "seed_topic_decimals",
      subject_id: "seed_subject_maths_g7",
      question_text: "Tapiwa has $5.00. He spends $3.75. How much is left?",
      question_type: "mcq",
      options: [{ label: "A", text: "$1.25" }, { label: "B", text: "$2.25" }, { label: "C", text: "$1.75" }, { label: "D", text: "$8.75" }],
      correct_answer: "A",
      explanation: "$5.00 - $3.75 = $1.25.",
      difficulty: "Standard",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_percentage_1",
      topic_id: "seed_topic_percentages",
      subject_id: "seed_subject_maths_g7",
      question_text: "What is 50 percent of 30 oranges?",
      question_type: "mcq",
      options: [{ label: "A", text: "10" }, { label: "B", text: "15" }, { label: "C", text: "20" }, { label: "D", text: "50" }],
      correct_answer: "B",
      explanation: "50 percent means half. Half of 30 is 15.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_percentage_2",
      topic_id: "seed_topic_percentages",
      subject_id: "seed_subject_maths_g7",
      question_text: "A test is marked out of 20. A pupil scores 16. What percentage is this?",
      question_type: "mcq",
      options: [{ label: "A", text: "60%" }, { label: "B", text: "70%" }, { label: "C", text: "80%" }, { label: "D", text: "90%" }],
      correct_answer: "C",
      explanation: "20 x 5 = 100, so 16 x 5 = 80 percent.",
      difficulty: "Standard",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_parts_speech_1",
      topic_id: "seed_topic_parts_of_speech",
      subject_id: "seed_subject_english_g7",
      question_text: "In the sentence 'The girl reads a book', which word is the verb?",
      question_type: "mcq",
      options: [{ label: "A", text: "girl" }, { label: "B", text: "reads" }, { label: "C", text: "book" }, { label: "D", text: "the" }],
      correct_answer: "B",
      explanation: "Reads is the action word, so it is the verb.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_parts_speech_2",
      topic_id: "seed_topic_parts_of_speech",
      subject_id: "seed_subject_english_g7",
      question_text: "Which word is an adjective in 'The red bus stopped'?",
      question_type: "mcq",
      options: [{ label: "A", text: "red" }, { label: "B", text: "bus" }, { label: "C", text: "stopped" }, { label: "D", text: "the" }],
      correct_answer: "A",
      explanation: "Red describes the bus, so it is an adjective.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_composition_1",
      topic_id: "seed_topic_composition",
      subject_id: "seed_subject_english_g7",
      question_text: "What should you do before writing a composition?",
      question_type: "mcq",
      options: [{ label: "A", text: "Plan your ideas" }, { label: "B", text: "Ignore the topic" }, { label: "C", text: "Write without checking" }, { label: "D", text: "Use one long paragraph" }],
      correct_answer: "A",
      explanation: "A plan helps you organise your beginning, middle, and ending.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_body_1",
      topic_id: "seed_topic_human_body",
      subject_id: "seed_subject_science_g7",
      question_text: "Which organ pumps blood around the body?",
      question_type: "mcq",
      options: [{ label: "A", text: "Heart" }, { label: "B", text: "Lung" }, { label: "C", text: "Stomach" }, { label: "D", text: "Ear" }],
      correct_answer: "A",
      explanation: "The heart pumps blood around the body.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_body_2",
      topic_id: "seed_topic_human_body",
      subject_id: "seed_subject_science_g7",
      question_text: "Which body part helps us breathe?",
      question_type: "mcq",
      options: [{ label: "A", text: "Lungs" }, { label: "B", text: "Teeth" }, { label: "C", text: "Knees" }, { label: "D", text: "Hair" }],
      correct_answer: "A",
      explanation: "The lungs help us take in and breathe out air.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_water_cycle_1",
      topic_id: "seed_topic_water_cycle",
      subject_id: "seed_subject_science_g7",
      question_text: "What is evaporation?",
      question_type: "mcq",
      options: [{ label: "A", text: "Water changing into vapour" }, { label: "B", text: "Rain falling" }, { label: "C", text: "Clouds becoming rocks" }, { label: "D", text: "Soil drying forever" }],
      correct_answer: "A",
      explanation: "Evaporation happens when liquid water changes into water vapour.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_water_cycle_2",
      topic_id: "seed_topic_water_cycle",
      subject_id: "seed_subject_science_g7",
      question_text: "Which process forms clouds?",
      question_type: "mcq",
      options: [{ label: "A", text: "Condensation" }, { label: "B", text: "Collection" }, { label: "C", text: "Harvesting" }, { label: "D", text: "Digestion" }],
      correct_answer: "A",
      explanation: "Condensation forms clouds when water vapour cools.",
      difficulty: "Standard",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_maps_1",
      topic_id: "seed_topic_maps",
      subject_id: "seed_subject_social_g7",
      question_text: "What does a map key explain?",
      question_type: "mcq",
      options: [{ label: "A", text: "Map symbols" }, { label: "B", text: "Only rivers" }, { label: "C", text: "Pupil names" }, { label: "D", text: "Weather only" }],
      correct_answer: "A",
      explanation: "A map key explains what symbols on the map mean.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_maps_2",
      topic_id: "seed_topic_maps",
      subject_id: "seed_subject_social_g7",
      question_text: "If a clinic is north of the school, which direction is it from the school?",
      question_type: "mcq",
      options: [{ label: "A", text: "North" }, { label: "B", text: "South" }, { label: "C", text: "East" }, { label: "D", text: "West" }],
      correct_answer: "A",
      explanation: "The question says the clinic is north of the school.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_history_1",
      topic_id: "seed_topic_zimbabwe_history",
      subject_id: "seed_subject_social_g7",
      question_text: "Which historical place is linked to the name Zimbabwe?",
      question_type: "mcq",
      options: [{ label: "A", text: "Great Zimbabwe" }, { label: "B", text: "Victoria Falls only" }, { label: "C", text: "Kariba Dam only" }, { label: "D", text: "A shopping mall" }],
      correct_answer: "A",
      explanation: "The country name Zimbabwe is linked to Great Zimbabwe.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_history_2",
      topic_id: "seed_topic_zimbabwe_history",
      subject_id: "seed_subject_social_g7",
      question_text: "When is Zimbabwe Independence Day observed?",
      question_type: "mcq",
      options: [{ label: "A", text: "18 April" }, { label: "B", text: "25 December" }, { label: "C", text: "1 January" }, { label: "D", text: "1 May" }],
      correct_answer: "A",
      explanation: "Zimbabwe Independence Day is observed on 18 April.",
      difficulty: "Standard",
      marks: 1,
      is_active: true,
    },
  ],
  practiceTests: [
    {
      id: "seed_practice_fractions_1",
      topic_id: "seed_topic_fractions",
      subject_id: "seed_subject_maths_g7",
      name: "Fractions Starter Test",
      test_number: 1,
      question_ids: ["seed_q_fraction_1", "seed_q_fraction_2"],
      type: "curated",
    },
    {
      id: "seed_practice_area_1",
      topic_id: "seed_topic_area",
      subject_id: "seed_subject_maths_g7",
      name: "Area and Perimeter Starter Test",
      test_number: 1,
      question_ids: ["seed_q_area_1"],
      type: "curated",
    },
    {
      id: "seed_practice_decimals_1",
      topic_id: "seed_topic_decimals",
      subject_id: "seed_subject_maths_g7",
      name: "Decimals and Money Starter Test",
      test_number: 1,
      question_ids: ["seed_q_decimal_1", "seed_q_decimal_2"],
      type: "curated",
    },
    {
      id: "seed_practice_percentages_1",
      topic_id: "seed_topic_percentages",
      subject_id: "seed_subject_maths_g7",
      name: "Percentages Starter Test",
      test_number: 1,
      question_ids: ["seed_q_percentage_1", "seed_q_percentage_2"],
      type: "curated",
    },
    {
      id: "seed_practice_comprehension_1",
      topic_id: "seed_topic_comprehension",
      subject_id: "seed_subject_english_g7",
      name: "Comprehension Starter Test",
      test_number: 1,
      question_ids: ["seed_q_comprehension_1"],
      type: "curated",
    },
    {
      id: "seed_practice_parts_speech_1",
      topic_id: "seed_topic_parts_of_speech",
      subject_id: "seed_subject_english_g7",
      name: "Parts of Speech Starter Test",
      test_number: 1,
      question_ids: ["seed_q_parts_speech_1", "seed_q_parts_speech_2"],
      type: "curated",
    },
    {
      id: "seed_practice_composition_1",
      topic_id: "seed_topic_composition",
      subject_id: "seed_subject_english_g7",
      name: "Composition Starter Test",
      test_number: 1,
      question_ids: ["seed_q_composition_1"],
      type: "curated",
    },
    {
      id: "seed_practice_plants_1",
      topic_id: "seed_topic_plants",
      subject_id: "seed_subject_science_g7",
      name: "Plant Growth Starter Test",
      test_number: 1,
      question_ids: ["seed_q_plants_1"],
      type: "curated",
    },
    {
      id: "seed_practice_body_1",
      topic_id: "seed_topic_human_body",
      subject_id: "seed_subject_science_g7",
      name: "Human Body Starter Test",
      test_number: 1,
      question_ids: ["seed_q_body_1", "seed_q_body_2"],
      type: "curated",
    },
    {
      id: "seed_practice_water_cycle_1",
      topic_id: "seed_topic_water_cycle",
      subject_id: "seed_subject_science_g7",
      name: "Water Cycle Starter Test",
      test_number: 1,
      question_ids: ["seed_q_water_cycle_1", "seed_q_water_cycle_2"],
      type: "curated",
    },
    {
      id: "seed_practice_maps_1",
      topic_id: "seed_topic_maps",
      subject_id: "seed_subject_social_g7",
      name: "Maps and Directions Starter Test",
      test_number: 1,
      question_ids: ["seed_q_maps_1", "seed_q_maps_2"],
      type: "curated",
    },
    {
      id: "seed_practice_history_1",
      topic_id: "seed_topic_zimbabwe_history",
      subject_id: "seed_subject_social_g7",
      name: "Zimbabwe History Starter Test",
      test_number: 1,
      question_ids: ["seed_q_history_1", "seed_q_history_2"],
      type: "curated",
    },
  ],
  mockExams: [
    {
      id: "seed_mock_exam_1",
      subject_id: "seed_subject_maths_g7",
      title: "Grade 7 Mathematics Offline Mock Exam",
      exam_number: 1,
      grade: "Grade 7",
      duration_minutes: 10,
      total_marks: 3,
      instructions: "Answer all questions. Choose the best answer.",
      question_ids: ["seed_q_fraction_1", "seed_q_fraction_2", "seed_q_area_1"],
      is_active: true,
    },
    {
      id: "seed_mock_exam_english_1",
      subject_id: "seed_subject_english_g7",
      title: "Grade 7 English Offline Mock Exam",
      exam_number: 1,
      grade: "Grade 7",
      duration_minutes: 10,
      total_marks: 4,
      instructions: "Answer all questions. Choose the best answer.",
      question_ids: ["seed_q_comprehension_1", "seed_q_parts_speech_1", "seed_q_parts_speech_2", "seed_q_composition_1"],
      is_active: true,
    },
    {
      id: "seed_mock_exam_science_1",
      subject_id: "seed_subject_science_g7",
      title: "Grade 7 Science Offline Mock Exam",
      exam_number: 1,
      grade: "Grade 7",
      duration_minutes: 10,
      total_marks: 5,
      instructions: "Answer all questions. Choose the best answer.",
      question_ids: ["seed_q_plants_1", "seed_q_body_1", "seed_q_body_2", "seed_q_water_cycle_1", "seed_q_water_cycle_2"],
      is_active: true,
    },
    {
      id: "seed_mock_exam_social_1",
      subject_id: "seed_subject_social_g7",
      title: "Grade 7 Social Studies Offline Mock Exam",
      exam_number: 1,
      grade: "Grade 7",
      duration_minutes: 10,
      total_marks: 4,
      instructions: "Answer all questions. Choose the best answer.",
      question_ids: ["seed_q_maps_1", "seed_q_maps_2", "seed_q_history_1", "seed_q_history_2"],
      is_active: true,
    },
  ],
};
