export const offlineSeed = {
  childProfiles: [
    {
      id: "seed_child_grade7",
      parent_email: "offline@zamaai.local",
      child_name: "Offline Learner",
      grade: "Grade 7",
      is_active: true,
      created_date: "2026-01-01T00:00:00.000Z",
    },
  ],
  subjects: [
    {
      id: "seed_subject_maths_g7",
      name: "Mathematics",
      grade: "Grade 7",
      icon: "➗",
      color: "violet",
      description: "Numbers, shapes, measurements, and problem solving.",
      is_active: true,
    },
    {
      id: "seed_subject_english_g7",
      name: "English",
      grade: "Grade 7",
      icon: "📘",
      color: "blue",
      description: "Reading, grammar, vocabulary, and writing skills.",
      is_active: true,
    },
    {
      id: "seed_subject_science_g7",
      name: "Science",
      grade: "Grade 7",
      icon: "🔬",
      color: "emerald",
      description: "Living things, matter, energy, and the environment.",
      is_active: true,
    },
  ],
  topics: [
    {
      id: "seed_topic_fractions",
      subject_id: "seed_subject_maths_g7",
      name: "Fractions",
      order: 1,
      learning_objectives: "Compare fractions and solve simple sharing problems.",
      description: "Learn how fractions show parts of a whole.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_area",
      subject_id: "seed_subject_maths_g7",
      name: "Area and Perimeter",
      order: 2,
      learning_objectives: "Find distance around a shape and space inside it.",
      description: "Use rectangles and real-life measurements.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_comprehension",
      subject_id: "seed_subject_english_g7",
      name: "Reading Comprehension",
      order: 1,
      learning_objectives: "Read a short passage and answer questions from it.",
      description: "Practise finding facts and meaning in a passage.",
      is_free: true,
      is_active: true,
    },
    {
      id: "seed_topic_plants",
      subject_id: "seed_subject_science_g7",
      name: "Plant Growth",
      order: 1,
      learning_objectives: "Identify what plants need to grow well.",
      description: "Explore water, sunlight, air, soil, and healthy plants.",
      is_free: true,
      is_active: true,
    },
  ],
  notes: [
    {
      id: "seed_note_fractions",
      topic_id: "seed_topic_fractions",
      subject_id: "seed_subject_maths_g7",
      overview: "A fraction shows part of a whole. If a sadza pot is shared into 4 equal parts, one part is 1/4.",
      key_definitions: "- Whole: the complete thing.\n- Equal parts: parts with the same size.\n- Fraction: one or more equal parts of a whole.",
      key_concepts: "To compare fractions, first check if the bottom numbers are the same. If they are the same, the bigger top number is the bigger fraction.",
      concept_examples: [
        {
          concept: "Sharing equally",
          examples: [
            { difficulty: "Easy", problem: "Tariro eats 1/4 of a mango. What fraction is eaten?", solution: "Step 1: The mango has 4 equal parts. Step 2: Tariro eats 1 part. Answer = 1/4." },
            { difficulty: "Standard", problem: "A cake is cut into 8 equal pieces. Tendai eats 3 pieces. What fraction is eaten?", solution: "Step 1: There are 8 pieces. Step 2: Tendai eats 3 pieces. Answer = 3/8." },
            { difficulty: "Hard", problem: "A farmer shares 12 oranges equally among 4 children. What fraction of all oranges does one child get?", solution: "Step 1: One child gets 3 oranges. Step 2: 3 out of 12 is 3/12. Step 3: 3/12 is the same as 1/4. Answer = 1/4." }
          ]
        }
      ],
      zimbabwe_examples: "Fractions are used when sharing sadza, cutting fruit, measuring mealie meal, or splitting bus fare.",
      important_facts: "- Fractions must have equal parts.\n- The top number counts selected parts.\n- The bottom number counts all equal parts.\n- Bigger bottom numbers can mean smaller pieces.",
      common_mistakes: "Do not compare only the bottom number. 1/2 is bigger than 1/4 because half is larger than a quarter.",
      summary: "- A fraction is part of a whole.\n- Parts must be equal.\n- 1/2 means one of two equal parts.\n- 3/4 means three of four equal parts.\n- Draw pictures when unsure.",
      exam_tips: "Draw the whole first. Split it into equal parts. Shade the parts asked for. Check your answer.",
      is_ai_generated: false,
      is_active: true,
    },
    {
      id: "seed_note_comprehension",
      topic_id: "seed_topic_comprehension",
      subject_id: "seed_subject_english_g7",
      overview: "Comprehension means understanding what you read. Read slowly and look for answers in the passage.",
      key_definitions: "- Passage: the text you read.\n- Main idea: what the passage is mostly about.\n- Detail: a small fact from the passage.",
      key_concepts: "Read the question first. Then scan the passage for key words. Use evidence from the passage.",
      concept_examples: [
        {
          concept: "Finding evidence",
          examples: [
            { difficulty: "Easy", problem: "A passage says Nyasha watered maize every morning. Who watered maize?", solution: "Step 1: Find the word watered. Step 2: Read the sentence. Answer = Nyasha." },
            { difficulty: "Standard", problem: "A story says rain clouds gathered, then pupils ran home. Why did they run?", solution: "Step 1: Look before the action. Step 2: Rain clouds gathered. Answer = They thought it would rain." },
            { difficulty: "Hard", problem: "A character shares food with a friend. What does this show?", solution: "Step 1: Notice the action. Step 2: Sharing helps someone. Step 3: This shows kindness. Answer = The character is kind." }
          ]
        }
      ],
      zimbabwe_examples: "You can read stories about school, markets, farms, buses, and family life in Zimbabwe.",
      important_facts: "- Read twice.\n- Underline key words.\n- Use the passage.\n- Do not guess before reading.",
      common_mistakes: "Do not answer from your own ideas only. The answer must match the passage.",
      summary: "- Read the question.\n- Find key words.\n- Read nearby sentences.\n- Choose the best answer.\n- Check again.",
      exam_tips: "If stuck, skip and come back. Answers often appear near the same words used in the question.",
      is_ai_generated: false,
      is_active: true,
    },
  ],
  questions: [
    {
      id: "seed_q_fraction_1",
      topic_id: "seed_topic_fractions",
      subject_id: "seed_subject_maths_g7",
      question_text: "A mango is cut into 4 equal pieces. Rudo eats 1 piece. What fraction did she eat?",
      question_type: "mcq",
      options: [{ label: "A", text: "1/2" }, { label: "B", text: "1/4" }, { label: "C", text: "3/4" }, { label: "D", text: "4/1" }],
      correct_answer: "B",
      explanation: "She ate 1 out of 4 equal pieces, so the fraction is 1/4.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_fraction_2",
      topic_id: "seed_topic_fractions",
      subject_id: "seed_subject_maths_g7",
      question_text: "Which fraction is larger?",
      question_type: "mcq",
      options: [{ label: "A", text: "1/2" }, { label: "B", text: "1/4" }, { label: "C", text: "1/8" }, { label: "D", text: "1/10" }],
      correct_answer: "A",
      explanation: "One half is bigger than one quarter, one eighth, and one tenth.",
      difficulty: "Standard",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_area_1",
      topic_id: "seed_topic_area",
      subject_id: "seed_subject_maths_g7",
      question_text: "A rectangular garden is 6 m long and 4 m wide. What is its area?",
      question_type: "mcq",
      options: [{ label: "A", text: "10 m²" }, { label: "B", text: "20 m²" }, { label: "C", text: "24 m²" }, { label: "D", text: "26 m²" }],
      correct_answer: "C",
      explanation: "Area of a rectangle = length × width. 6 × 4 = 24 m².",
      difficulty: "Standard",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_comprehension_1",
      topic_id: "seed_topic_comprehension",
      subject_id: "seed_subject_english_g7",
      comprehension_passage: "Nyasha woke up early in Mutare. She helped her grandmother water the vegetable garden before school. The tomatoes were growing well because they had enough water and sunlight.",
      question_text: "Why were the tomatoes growing well?",
      question_type: "comprehension",
      options: [{ label: "A", text: "They had enough water and sunlight" }, { label: "B", text: "Nyasha slept late" }, { label: "C", text: "It was raining all day" }, { label: "D", text: "They were at school" }],
      correct_answer: "A",
      explanation: "The passage says the tomatoes had enough water and sunlight.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
    {
      id: "seed_q_plants_1",
      topic_id: "seed_topic_plants",
      subject_id: "seed_subject_science_g7",
      question_text: "Which of these do green plants need to make food?",
      question_type: "mcq",
      options: [{ label: "A", text: "Sunlight" }, { label: "B", text: "Plastic" }, { label: "C", text: "Smoke" }, { label: "D", text: "Salt only" }],
      correct_answer: "A",
      explanation: "Green plants need sunlight, air, and water to make food.",
      difficulty: "Easy",
      marks: 1,
      is_active: true,
    },
  ],
  practiceTests: [
    {
      id: "seed_practice_fractions_1",
      topic_id: "seed_topic_fractions",
      subject_id: "seed_subject_maths_g7",
      name: "Fractions Starter Test",
      test_number: 1,
      question_ids: ["seed_q_fraction_1", "seed_q_fraction_2"],
      type: "curated",
    },
    {
      id: "seed_practice_comprehension_1",
      topic_id: "seed_topic_comprehension",
      subject_id: "seed_subject_english_g7",
      name: "Comprehension Starter Test",
      test_number: 1,
      question_ids: ["seed_q_comprehension_1"],
      type: "curated",
    },
  ],
  mockExams: [
    {
      id: "seed_mock_exam_1",
      subject_id: "seed_subject_maths_g7",
      title: "Grade 7 Mathematics Offline Mock Exam",
      exam_number: 1,
      grade: "Grade 7",
      duration_minutes: 10,
      total_marks: 3,
      instructions: "Answer all questions. Choose the best answer.",
      question_ids: ["seed_q_fraction_1", "seed_q_fraction_2", "seed_q_area_1"],
      is_active: true,
    },
  ],
};
